spring:
  application:
    name: eLearningAPI

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    generate-ddl: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      schema-locations: classpath:01-schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8081