name: test

on: [push , pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
 
      - name: ls
        run: ls -al

                    
      - name: Setup Java JDK              
        uses: actions/setup-java@v4.4.0
        with:
          distribution: temurin
          java-version: '17'

      - name: Test
        run: mvn test

      - name: build and package project
        run: mvn package -DskipTests

      - name: show target
        run: ls -la target


      - name: show principal
        run: ls -la

      - name: Show ls and navigate to target
        run: |
          ls
          cd target
          ls -al








  ls:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: ls
        run: ls -al
  